### ISSUE TITLE
[Flutter Windows]: failure when creating MSIX installer

### ISSUE THREAD

**Issue by matthiasn** [matthiasn/lotti#942]
I'm trying to build and MSIX installer for Windows and I run into this issue:

```
flutter pub run msix:create
--
  | running "flutter build windows"...
  |  
  | Building with sound null safety
  |  
  | Building Windows application...
  |  
  | Unhandled exception:
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/connectivity_plus_windows/windows"
  | which is not an existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_windows/windows"
  | which is not an existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/hotkey_manager/windows" which is not an
  | existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/permission_handler_windows/windows"
  | which is not an existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/sqlite3_flutter_libs/windows" which is
  | not an existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows" which is
  | not an existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | CMake Error at flutter/generated_plugins.cmake:18 (add_subdirectory):
  | add_subdirectory given source
  | "flutter/ephemeral/.plugin_symlinks/window_manager/windows" which is not an
  | existing directory.
  | Call Stack (most recent call first):
  | CMakeLists.txt:51 (include)
  |  
  |  
  | Unable to generate build files
  |  
  | #0      WindowsBuild.build (package:msix/src/windows_build.dart:32:7)
  | <asynchronous suspension>
  | #1      Msix._buildMsixFiles (package:msix/msix.dart:107:7)
  | <asynchronous suspension>
  | #2      Msix._createMsix (package:msix/msix.dart:101:5)
  | <asynchronous suspension>
  | #3      Msix.create (package:msix/msix.dart:71:5)
  | <asynchronous suspension>
  | #4      main (file:///c:/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.5.1/bin/create.dart:4:3)
  | <asynchronous suspension>
  | pub finished with exit code 255
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1
```

**Comment by matthiasn** [comment]
Fixed, will add a step for uploading to GitHub Releases in CI.
